In [ ]:
# 1. What is a Python library? Why do we use Python libraries?

# 1. **Definition:**
#    - A Python library is a collection of pre-written code and functions that provide reusable tools and resources for developers.
   
# 2. **Functionality:**
#    - Libraries offer a set of modules and functions that can be imported into Python scripts to perform specific tasks.
  
# 3. **Code Reusability:**
#    - Libraries save time and effort by allowing developers to leverage existing code, avoiding the need to reinvent the wheel for common tasks.

# 4. **Efficiency:**
#    - Using libraries can enhance code efficiency, as they are typically optimized and tested for performance and reliability.

# 5. **Specialized Capabilities:**
#    - Libraries often focus on specific domains or tasks, providing specialized functionality that may be challenging or time-consuming to implement from scratch.

# 6. **Community Contribution:**
#    - Python libraries are often developed and maintained by a community of programmers, fostering collaboration and knowledge-sharing.

# 7. **Enhanced Productivity:**
#    - Leveraging libraries allows developers to build on top of well-established and tested components, accelerating the development process.

# 8. **Standardization:**
#    - Libraries help establish common practices and standards within the Python ecosystem, promoting consistency across different projects and industries.

In [ ]:
# 2. What is the difference between Numpy array and List?


# 1. **Data Type:**
#    - **List:** Lists in Python can contain elements of different data types.
#    - **Numpy Array:** Numpy arrays are homogeneous and contain elements of the same data type.

# 2. **Performance:**
#    - **List:** Lists are generally slower for numerical operations compared to numpy arrays.
#    - **Numpy Array:** Numpy arrays are more efficient for numerical computations due to their fixed data type and contiguous memory allocation.

# 3. **Memory Usage:**
#    - **List:** Lists consume more memory as they store additional information (type information, references, etc.) for each element.
#    - **Numpy Array:** Numpy arrays are more memory-efficient as they store data in a contiguous block and have a fixed data type.

# 4. **Functionality:**
#    - **List:** Lists offer a variety of general-purpose methods and functionalities.
#    - **Numpy Array:** Numpy arrays provide extensive mathematical operations and functions optimized for array operations.

# 5. **Syntax:**
#    - **List:** Lists are built into the core Python language.
#    - **Numpy Array:** Numpy is a separate library, and its arrays need to be imported (`import numpy as np`), and then arrays are created using `np.array()`.

# 6. **Ease of Use:**
#    - **List:** Lists are generally easier to work with for simple, non-mathematical tasks.
#    - **Numpy Array:** Numpy arrays are more suitable for numerical computations and tasks involving large datasets.

# 7. **Flexibility:**
#    - **List:** Lists offer more flexibility in terms of operations and can contain elements of different types.
#    - **Numpy Array:** Numpy arrays are specialized for numerical operations and may not be as versatile as lists for certain tasks.

In [4]:
# 3. Find the shape, size and dimension of the following array?
arr = [[1, 2, 3, 4],
      [5, 6, 7, 8],
       [9, 10, 11, 12]]

In [6]:
arr1 = np.array(arr)

In [8]:
arr1.shape

(3, 4)

In [9]:
arr1.size

12

In [10]:
arr1.ndim

2

In [11]:
# 4. Write python code to access the first row of the following array?
arr = [[1, 2, 3, 4],
      [5, 6, 7, 8],
     [9, 10, 11, 12]]

In [12]:
arr1 = np.array(arr)

In [14]:
arr1[0]

array([1, 2, 3, 4])

In [15]:
# 5. How do you access the element at the third row and fourth column from the given numpy array?
arr = [[1, 2, 3, 4],
      [5, 6, 7, 8],
     [9, 10, 11, 12]]

In [16]:
arr1 = np.array(arr)

In [21]:
arr1[2,3]

12

In [22]:
# 6. Write code to extract all odd-indexed elements from the given numpy array?
arr = [[1, 2, 3, 4],
      [5, 6, 7, 8],
      [9, 10, 11, 12]]

In [23]:
arr1 = np.array(arr)

In [24]:
arr1[arr1 % 2 != 0]

array([ 1,  3,  5,  7,  9, 11])

In [31]:
# 7. How can you generate a random 3x3 matrix with values between 0 and 1?

arr2 = np.random.rand(3,3)
arr2

array([[0.23051739, 0.16707887, 0.48942874],
       [0.01137886, 0.11958951, 0.43829645],
       [0.11287761, 0.48109975, 0.28155538]])

In [32]:
type(arr2)

numpy.ndarray

In [ ]:
# 8. Describe the difference between np.random.rand and np.random.randn?

# The `np.random.rand` and `np.random.randn` functions in NumPy are both used for generating random numbers,
# but they differ in terms of the distribution from which the random numbers are drawn:

# 1. `np.random.rand`:
#    - Generates random numbers from a uniform distribution over the half-open interval [0.0, 1.0).
#    - All values in the output array are equally likely to occur.
#    - Takes the shape of the array as individual arguments (not as a tuple).


# 2. `np.random.randn`:
#    - Generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).
#    - Values are more likely to be close to 0, and the distribution follows a bell curve.
#    - Takes the shape of the array as individual arguments (not as a tuple).



In [38]:
# 9. Write code to increase the dimension of the following array?
arr = [[1, 2, 3, 4],
      [5, 6, 7, 8],
      [9, 10, 11, 12]]

In [39]:
arr1 = np.array(arr)

In [52]:
arr2 = arr1[:,:,np.newaxis]

In [50]:
arr2

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]]])

In [51]:
arr2.ndim

3

In [33]:
# 10. How to transpose the following array in NumPy?
arr= [[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]]

In [34]:
arr1 = np.array(arr)

In [35]:
arr1.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [54]:
# 11. Consider the following matrix:
Matrix_A2 = [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix_B2 = [[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]]
# Perform the following operation using Python1
# 1. Index wiSe multiplication
#  2.Matix multiplication
# 3. Add both the matices
# 4. Subtact matix B from A 
# 5.Divide Matix B by A

In [55]:
arr1 = np.array(Matrix_A2)
arr2 = np.array(Matrix_B2)

In [59]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [60]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
arr1 * arr2 # 1.Index wise multiplication

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [ ]:
arr1@arr2 #2.matrix multiplication is not possible because of same order (n,k),(k,m)->(n,m)

In [65]:
arr2_transposed = arr2.T

arr1 @arr2_transposed # by transposing the arr2 matrix we can perform matrix multiplication

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [66]:
# 3. Add both the matices
arr1 + arr2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [67]:
# 4. Subtact matix B from A 
arr2 - arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [68]:
# 5.Divide Matix B by A
arr2 / arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [69]:
# 12. Which function in Numpy can be used to swap the byte order of an array?

import numpy as np

original_array = np.array([1, 2, 3, 4], dtype=np.int32)
print("Original Array:")
print(original_array)

# Swap the byte order
swapped_array = original_array.byteswap()
print("\nArray after byte swapping:")
print(swapped_array)
 


Original Array:
[1 2 3 4]

Array after byte swapping:
[16777216 33554432 50331648 67108864]


In [70]:
# 13. What is the significance of the np.linalg.inv function?

# The `np.linalg.inv` function in NumPy is used to compute the (multiplicative) inverse of a square matrix. 
# In linear algebra, the inverse of a matrix A is denoted as \(A^{-1}\), and it has the property that when it is multiplied by the original matrix A, 
# the result is the identity matrix (\(A \cdot A^{-1} = A^{-1} \cdot A = I\), where I is the identity matrix).

# Here are some key points regarding the significance of `np.linalg.inv`:

# 1. **Solving Linear Systems:** One of the primary uses of matrix inversion is in solving systems of linear equations. 
# If you have a system of equations in the form \(Ax = B\), where A is a square matrix of coefficients, x is a column vector of variables,
# and B is a column vector of constants, you can solve for x by finding the inverse of A: \(x = A^{-1}B\).

# 2. **Computing Determinants:** The inverse of a matrix A exists if and only if the determinant of A is non-zero. 
# The determinant can be computed using `np.linalg.det`. Checking for a non-zero determinant is essential before attempting to compute the inverse.

# 3. **Numerical Stability:** While the mathematical concept of matrix inversion is well-defined, 
# in numerical computations, especially with floating-point numbers, there can be precision issues. 
# The `np.linalg.inv` function uses efficient and numerically stable algorithms to compute the inverse.

# example:

import numpy as np

A = np.array([[2, 1],
              [7, 4]])

A_inv = np.linalg.inv(A)

print("Original Matrix:")
print(A)

print("\nInverse Matrix:")
print(A_inv)



Original Matrix:
[[2 1]
 [7 4]]

Inverse Matrix:
[[ 4. -1.]
 [-7.  2.]]


In [ ]:
# 14. What does the np.reshape function do, and how is it used?

# The `np.reshape` function in NumPy is used to give a new shape to an array without changing its data.
# It returns a new array with the specified shape while maintaining the same data. 
# The reshaping operation is particularly useful when you want to rearrange the elements of an array without changing their values.

# The syntax for `np.reshape` is as follows:

# numpy.reshape(a, newshape, order='C')


# - `a`: The array to be reshaped.
# - `newshape`: The new shape (tuple of integers) that you want to give to the array.
# - `order`: (Optional) Specifies the order in which the elements are read. It can be 'C' for C-style (row-major) or 'F' for Fortran-style (column-major).
# The default is 'C'.


# It's important to note that the total number of elements in the original array must match the total number of elements in the reshaped array. 
# The `np.reshape` function allows you to change the arrangement of elements, but it does not change the total number of elements.

# If you want to automatically infer one of the dimensions based on the size of the array, you can use `-1` in the `newshape`. 

# # Reshape to 3 rows and automatically infer the number of columns
# reshaped_array = np.reshape(original_array, (3, -1))

# In this case, NumPy will automatically calculate the number of columns based on the total number of elements and the specified number of rows.


In [ ]:
# 15. What is broadcasting in Numpy?

Broadcasting in NumPy is a powerful mechanism that allows for performing operations on arrays of different shapes and sizes. 
It enables you to apply element-wise operations between arrays of different shapes without the need for explicit looping or unnecessary replication of data.
Broadcasting makes the code more concise and often more efficient.

The basic idea behind broadcasting is to automatically expand the smaller array to match the shape of the larger array so that they can be combined in a meaningful way. The broadcasting rules define how these operations are carried out.

The two arrays are compatible for broadcasting if, for each dimension, either the dimensions are the same or one of them is 1. The smaller array is "broadcast" across the larger array to make their shapes compatible.

Here's a simple example to illustrate broadcasting:

```python
import numpy as np

# Create a 3x3 matrix
matrix_A = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Create a 1D array
array_B = np.array([10, 20, 30])

# Broadcasting: Add the array to each row of the matrix
result = matrix_A + array_B

print("Matrix A:")
print(matrix_A)

print("\nArray B:")
print(array_B)

print("\nResult after broadcasting:")
print(result)
```

In this example, the 1D array `array_B` is automatically broadcasted to the shape of the 3x3 matrix `matrix_A`, and then the addition operation is performed element-wise. The result is a new 3x3 matrix where each element is the sum of the corresponding elements in the original matrix and the broadcasted array.

Broadcasting is not limited to binary operations; it also works with unary operations and more complex operations involving multiple arrays.

Understanding broadcasting is crucial for efficient and readable NumPy code, especially when working with arrays of different shapes in scientific computing and data analysis.